# Generated by Django 4.2.6 on 2023-10-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_board_project'),
        ('projects', '0010_delete_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='boards',
            field=models.ManyToManyField(blank=True, related_name='project_boards', to='boards.board'),
        ),
    ]
