# Generated by Django 4.2.6 on 2023-10-15 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_delete_boards'),
        ('boards', '0013_auto_20201023_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_boards', to='projects.project'),
        ),
    ]
