# Generated by Django 4.2.6 on 2023-10-11 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='creator',
            new_name='Admin',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='workspace_tasks',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='workspace_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkspaceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='users.workspace')),
            ],
        ),
    ]
