# Generated by Django 4.2.6 on 2023-10-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_task_acheived'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacetask',
            name='acheived',
            field=models.BooleanField(default=False),
        ),
    ]
